name: Create README

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create README if missing
        run: |
          if [ ! -f README.md ]; then
            echo "# Worker Test" > README.md
            echo "Creating README.md file..."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "Add README.md"
            git push
          else
            echo "README.md already exists, skipping creation."
          fi